# Generated by Django 3.0.4 on 2020-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_desc', models.CharField(max_length=150)),
                ('issue_priority', models.CharField(max_length=6)),
                ('issue_assigned_to', models.CharField(max_length=100)),
            ],
        ),
    ]
